<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Make parameters safe and validate them
//
if (isset($div_spec)) $div_spec = kix\k::Safe($div_spec,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
if (isset($first_id_in_div)) $first_id_in_div = kix\k::Safe($first_id_in_div,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($last_id_in_div)) $last_id_in_div = kix\k::Safe($last_id_in_div,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
if (sscanf($div_spec,"%1d%1d%1d%1d-%1d%s",$d11,$d12,$d13,$d14,$d15,$d16) != 6)
   {
   echo "Improperly-formatted request";
   exit;
   }
//
require_once("f_bodyopen.phtml");
require_once("f_putlibphoto.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
extract(mysqli_fetch_array($db_link->query("select min(id) as first_id_in_div, max(id) as last_id_in_div from photo_detail where div_spec = \"$div_spec\"")));
?>
<html>
   <head><title>Frames on DIV <? echo $div_spec; ?></title></head>
   <? BodyOpen(); ?>
      <H6 ALIGN="CENTER">
         <a href="<? echo $ini[app][my_home_page_url]; ?>">Kevin Andrew Lipscomb</a>
         -
         <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a>
         -
         <a href="<? echo $ini[server][root_url]; ?>/browse_divs.phtml">Digital Image Volumes</a>
      </H6>
      <H1 ALIGN="CENTER">Frames on DIV <? echo $div_spec; ?></H1>
      <hr>
      <table align=center cellpadding="10" width="100%">
         <tr>
            <td align="right" valign="top" width="10%">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               if ($first_id_in_div > 1)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec from photo_detail where id = $first_id_in_div - 1")));
                  echo "<a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/browse_frames.phtml?div_spec=$prior_frame_div_spec><br/>Prior<br/>DIV<br/>&nbsp;</a>\n";
                  }
               ?>
               </tt>
            </td>
            <td width="80%">
               <center>
                  <?
                  $d = dir("div/$div_spec");
                  while ($filename = $d->read())
                     {
                     if (strstr($filename,"-i.jpg"))
                        {
                          PutLibPhoto($ini,$db_link,$div_spec,substr($filename,0,(strlen($filename) - 6)));
                        echo " ";
                        }
                     }
                  $d->close();
                  ?>
               </center>
            </td>
            <td align="left" valign="top" width="10%">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               extract(mysqli_fetch_array($db_link->query("select max(id) as max_id from photo_detail")));
               if ($last_id_in_div < $max_id)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec from photo_detail where id = $last_id_in_div + 1")));
                  echo "<a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/browse_frames.phtml?div_spec=$prior_frame_div_spec><br/>Next<br/>DIV<br/>&nbsp;</a>";
                  }
               ?>
               </tt>
            </td>
         </tr>
      </table>
   </body>
</html>
