<?
//
// $Id$
//
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>
<html>
   <head><title>Digital Image Volumes</title></head>
   <? BodyOpen(); ?>
      <table align=center width="80%">
         <tr>
            <td>
               <H6 ALIGN="CENTER"><a href="<? echo $ini[app][my_home_page_url]; ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></H6>
               <H1 ALIGN="CENTER">Digital Image Volumes</H1>
               <hr>
               <?
               echo "<ul>";
               $d = dir("../photo/div");
               while ($entry = $d->read())
                  {
                  if (!strstr($entry,"."))
                     {
                     $subdir_array[] = $entry;
                     }
                  }
               rsort($subdir_array);
               foreach ($subdir_array as $subdir)
                  {
                  echo "<li><a href=" . $ini[server][root_url] . "/browse_frames.phtml?div_spec=$subdir>$subdir</a>";
                  }
               echo "</ul>";
               $d->close();
               ?>
            </td>
         </tr>
      </table>
   </body>
</html>
