<?
//
// $Id$
//
require_once("f_myhomepageurl.phtml");
require_once("f_mymainphotopageurl.phtml");
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
?>
<html>
<head><title>Digital Image Volumes</title></head>
<? BodyOpen(); ?>
<table align=center width="80%"><tr><td>
<H6 ALIGN="CENTER"><a href="<? echo MyHomePageUrl(); ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo MyMainPhotoPageUrl(); ?>">Photography</a></H6>
<H1 ALIGN="CENTER">Digital Image Volumes</H1>
<hr>
<?
echo "<ul>";
$d = dir("div");
while ($subdir = $d->read())
   {
   if (!strstr($subdir,"."))
      {
      echo "<li><a href=http://kalipso.phpwebhosting.com/browse_frames.phtml?div_spec=$subdir>$subdir</a>";
      }
   }
echo "</ul>";
$d->close();
?>
</td></tr></table>
</body>
</html>
