<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Validate parameters
//
if (sscanf($div_spec,"%1d%1d%1d%1d-%1d%s",&$d11,&$d12,&$d13,&$d14,&$d15,&$d16) != 6)
   {
   echo "Improperly-formatted request";
   exit;
   }
require_once("f_myhomepageurl.phtml");
require_once("f_mymainphotopageurl.phtml");
require_once("f_putlibphoto.phtml");
require_once('f_putstdrecaptchablock.phtml');
require_once("f_bodyopen.phtml");
?>
<html>
<head><title>Anecdote/comment entry form [div/<? echo $div_spec ?>/<? echo $frame_num ?>]</title></head>
<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
         <H6 ALIGN="CENTER"><a href="<? echo MyHomePageUrl(); ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo MyMainPhotoPageUrl(); ?>">Photography</a></H6>
         <H1 ALIGN="CENTER">Anecdote/comment entry form</H1>
         <hr>
         <?
         PutLibPhoto($div_spec,$frame_num,"left");
         //
         echo "<br clear=both><br>\n";
         echo "<form action=add-comment.phtml method=post>\n";
         echo "<p>Your anecdote or comment:<br><textarea name=text rows=10 cols=65 wrap=soft></textarea></p>\n";
         echo "<p>Your name:<br><input name=nickname type=text size=40></p>\n";
         echo "<p>Your email address:<br><input name=email_address type=text size=40></p>";
         PutStdReCaptchaGetBlock();
         echo "<input name=div_spec value=$div_spec type=hidden>\n";
         echo "<input name=frame_num value=$frame_num type=hidden>\n";
         echo "<p><input type=submit value=Submit></p>\n";
         echo "</form>\n";
         ?>
      </td>
   </tr>
</table>
</body>
</html>
