<?
require_once("f_putlibphotoplaced.phtml");
require_once("f_bodyopen.phtml");
//
ParseIniAndConnectSelectDbInstance($ini,$db_link);
?>

<html>

<head>
<title>Photography - EMS</title>
</head>

<? BodyOpen(); ?>
<center>
<table border="0" cellpadding="0" cellspacing="0" width="80%">
  <tr>
    <td width="100%"><h5 align="center"><a href="<? echo $ini[app][my_home_page_url]; ?>">Kevin Andrew Lipscomb</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></h5>
      <h1 align="center">EMS</h1>
      <p align="center">
      <? PutLibPhotoPlaced($ini,$db_link,"ems"); ?>
      </p>
    </td>
  </tr>
</table>
</center>
</body>
</html>
