<?
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Make parameters safe and validate them
//
if (isset($era)) $era = kix\k::Safe($era,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
require_once("f_bodyopen.phtml");
//
ParseIniAndConnectSelectDbInstance($ini,$db_link);
?>

<html>

<head>
<title>Photography - <? echo "$subtitle"; ?></title>
</head>

<? BodyOpen(); ?>
<center>
<table border="0" cellpadding="0" cellspacing="0" width="80%">
  <tr>
    <td width="100%"><h5 align="center"><a href="<? echo $ini[app][my_home_page_url]; ?>">Kevin Andrew Lipscomb</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></h5>
      <h1 align="center"><? echo "$subtitle"; ?></h1>
      <p align="center">
      <?
      $result_set = $db_link->query("select div_spec,frame_num from photo_detail where era = '$era' order by rand()");
      //
      // Check how many rows were returned
      //
      $rows = mysqli_num_rows($result_set);
      if ((!$result_set) || ($rows == 0))
         {
         echo "<br><b>Could not find any such photographs.</b><br>";
         }
      else
         {
         //
         while ($field_array = mysqli_fetch_array($result_set))
            {
            extract($field_array);
               //
               // This sets up the $div_spec and $frame_num variables.
               //
            $image_source_spec = $ini[server][photodb_prefix] . "div/$div_spec/$frame_num-i.jpg";
            echo "<a href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>\n";
            $size = @GetImageSize("$image_source_spec");
            echo "   <img border=\"2\" src=\"$image_source_spec\" $size[3]>\n";
            echo "</a>\n";
            }
         }
      ?>
      </p>
    </td>
  </tr>
</table>
</center>
</body>
</html>
