<?
//
// $Id$
//
require_once("f_password.phtml");
//
function PutLibPhotoRandom($alignment = "")
   {
   //
   // Connect to the database.
   //
   $conn = mysql_connect(localhost,kalipso,Password());
   mysql_select_db(kalipso);
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail order by rand() limit 1";
   //
   // Execute the statement
   //
   $result_set = mysql_query($sql);
   //
   // Check how many rows were returned
   //
   $rows = mysql_num_rows($result_set);
   if ((!$result_set) || ($rows != 1))
      {
      echo "<br><b>Random photo retrieval failed.</b><br>";
      }
   else
      {
      //
      // We know exactly one row matched.  Fetch it.
      //
      $field_array = mysql_fetch_array($result_set);
      extract($field_array);
         //
         // This sets up the $div_spec and $frame_num variables.
         //
      $image_source_spec = "div/$div_spec/$frame_num-i.jpg";
      echo "<a href=\"http://kalipso.phpwebhosting.com/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num\">";
      $size = GetImageSize("$image_source_spec");
      echo "<img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>";
      echo "</a>";
      }
   }
?>
