<?
//
// $Id$
//
function PutLibPhotoRandomKeyed
   (
   $ini,
   $db_link,
   $key,
   $alignment = ""
   )
   {
   if (isset($key)) $key = kix\k::Safe($key,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail where caption like '$key' or tech_details like '$key' or keywords like '$key' order by rand()";
   //
   // Execute the statement
   //
   $result_set = $db_link->query($sql);
   //
   // Check how many rows were returned
   //
   $rows = mysqli_num_rows($result_set);
   if ((!$result_set) || ($rows == 0))
      {
      echo "<br><b>Could not find any such photographs.</b><br>";
      }
   else
      {
      //
      while ($field_array = mysqli_fetch_array($result_set))
         {
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = $ini[server][photodb_prefix] . "div/$div_spec/$frame_num-i.jpg";
         echo "<a href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>\n";
         $size = @GetImageSize("$image_source_spec");
         echo "   <img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>\n";
         echo "</a>\n";
         }
      }
   }
?>
