<?
//
// $Id$
//
require_once("f_myphotolibhosturl.phtml");
//
function PutLibPhoto
   (
   $div_spec,
   $frame_num,
   $alignment = ""
   )
   {
   $image_source_spec = "div/$div_spec/$frame_num-i.jpg";
   echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>";
   $size = @GetImageSize("$image_source_spec");
   echo "<img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>";
   echo "</a>";
   }
?>