<?
//
// $Id: f_putlibphotorandom.phtml 7622 2021-12-14 02:19:54Z kevinanlipscomb $
//
function PutLibPhotoRandom
   (
   $ini,
   $db_link,
   $alignment = ""
   )
   {
   require_once('f_beremotefileexistant.phtml');
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail order by rand() limit 1";
   //
   //
   $done = FALSE;
   while (!$done)
      {
      //
      // Execute the statement
      //
      $result_set = $db_link->query($sql)
         or die(mysqli_error($db_link));
      //
      // Check how many rows were returned
      //
      $rows = mysqli_num_rows($result_set);
      if ((!$result_set) || ($rows != 1))
         {
         echo "<br><b>Random photo retrieval failed.</b><br>";
         }
      else
         {
         //
         // We know exactly one row matched.  Fetch it.
         //
         $field_array = mysqli_fetch_array($result_set);
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = $ini[server][photodb_prefix] . "div/$div_spec/$frame_num-i.jpg";
         $size = GetImageSize($image_source_spec); // Should always work outside of development instance
         if ($size || BeRemoteFileExistant($image_source_spec)) // BeRemoteFileExistant() should suffice in deveopment instance, but dynamic image layout will be evident
            {
            echo "<a href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>";
            echo "<img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>";
            echo "</a>";
            $done = TRUE;
            }
         else if ($ini[app][be_d])
            {
            $done = TRUE;
            echo "No such frame.";
            }
         else
            {
            $db_link->query("delete from photo_detail where div_spec = '$div_spec' and frame_num = '$frame_num'");
            }
         }
      }
   }
?>
