<?
//
// $Id$
//
require_once("f_password.phtml");
require_once("f_myphotolibhosturl.phtml");
//
function PutLibPhotoRandomKeyed
   (
   $key,
   $alignment = ""
   )
   {
   //
   // Connect to the database.
   //
   $conn = mysql_connect("localhost","kalipso",Password());
   mysql_select_db("kalipso");
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail where caption like '$key' or tech_details like '$key' or keywords like '$key' order by rand()";
   //
   // Execute the statement
   //
   $result_set = mysql_query($sql);
   //
   // Check how many rows were returned
   //
   $rows = mysql_num_rows($result_set);
   if ((!$result_set) || ($rows == 0))
      {
      echo "<br><b>Could not find any such photographs.</b><br>";
      }
   else
      {
      //
      while ($field_array = mysql_fetch_array($result_set))
         {
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = "div/$div_spec/$frame_num-i.jpg";
         echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>\n";
         $size = @GetImageSize("$image_source_spec");
         echo "   <img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>\n";
         echo "</a>\n";
         }
      }
   }
?>
