<?
//
// $Id$
//
function PutLibPhotoRandom($alignment = "")
   {
   //
   // Connect to the database.
   //
   $conn = ConnectSelectDbInstanceUNPUBLISHED($db_link);
   $instance = Instance($db_link);
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail order by rand() limit 1";
   //
   //
   $done = FALSE;
   while (!$done)
      {
      //
      // Execute the statement
      //
      $result_set = $db_link->query($sql);
      //
      // Check how many rows were returned
      //
      $rows = mysqli_num_rows($result_set);
      if ((!$result_set) || ($rows != 1))
         {
         echo "<br><b>Random photo retrieval failed.</b><br>";
         }
      else
         {
         //
         // We know exactly one row matched.  Fetch it.
         //
         $field_array = mysqli_fetch_array($result_set);
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = "$instance[photodb_prefix]div/$div_spec/$frame_num-i.jpg";
         $size = @GetImageSize($image_source_spec); // Should always work outside of development instance
         if ($size || curl_init($image_source_spec)) // curl_init() should suffice in deveopment instance, but dynamic image layout will be evident
            {
            echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>";
            echo "<img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>";
            echo "</a>";
            $done = TRUE;
            }
         else if ($instance[be_d])
            {
            $done = TRUE;
            }
         else
            {
            $db_link->query("delete from photo_detail where div_spec = '$div_spec' and frame_num = '$frame_num'");
            }
         }
      }
   }
?>
