<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Make parameters safe and validate them
//
if (isset($time)) $time = kix\k::Safe($time,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($visitor)) $visitor = kix\k::Safe($visitor,kix\k::PhpValueOf_safe_hint_type("HEX"));
//
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
//
ParseIniAndConnectSelectDbInstance($ini,$db_link);
?>
<html>
<head><title>Mark Visit</title></head>
<? BodyOpen(); ?>
<table align=center width="80%"><tr><td>
<H6 ALIGN="CENTER"><a href="<? echo $ini[app][my_home_page_url]; ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></H6>
<H1 ALIGN="CENTER">Mark Visit</H1>
<hr>
<?
$time = time();
$sql = "replace visit (visitor,time) values (\"$visitor\",$time)";
$db_link->query($sql) or die("Sorry, the database update failed.");
?>
<p><b>Your current visit has been recorded and your list of new or updated Digital Image Volumes has been reset.</b></p>
</td></tr></table>
</body>
</html>
