<HTML>
<HEAD>
<TITLE>Photo Resume</TITLE>
</HEAD>

<?
require_once("f_putlibphotorandom.phtml");
require_once("f_bodyopen.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
BodyOpen();
?>

<P ALIGN="CENTER"><CENTER><TABLE CELLSPACING=0 BORDER=0 CELLPADDING=7 WIDTH="80%">
<TR><TD VALIGN="TOP">
<H6 ALIGN="CENTER"><a href="<? echo $ini[app][my_home_page_url]; ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></H6>
<H1 ALIGN="CENTER">Photo Resume</H1>
<hr>
<p><? PutLibPhotoRandom($ini,$db_link,"left"); ?>My photographs have been published as follows:</p>
<table><tr><td>
  <ul>
  <li>In <i>Dynamic Designs</i>, ISBN 0-7951-5083-0, published by <a href=http://www.picture.com>The International Library of Photography</a>, 2001.</li>
  <li>On the <a href="http://www.kvrs.org">Kempsville Volunteer Rescue Squad</a>'s
    web site;</li>
  <li>In Kempsville Volunteer Rescue Squad public relations material;</li>
  <li>In my junior high school and high school yearbooks.</li>
  </ul>
</td></tr></table>
  </TD>
</TR>
</TABLE>
</CENTER>

<pre><small><small><i>$Id: photo-resume.phtml 7086 2020-04-28 18:54:35Z kevinanlipscomb $</i></small></small></pre>
</HTML>
