<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Make parameters safe and validate them
//
if (isset($div_spec)) $div_spec = kix\k::Safe($div_spec,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
if (isset($frame_num)) $frame_num = kix\k::Safe($frame_num,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_UNDERSCORED_ALPHANUM"));
if (isset($id)) $id = kix\k::Safe($id,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($result_num)) $result_num = kix\k::Safe($result_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($search_id)) $search_id = kix\k::Safe($search_id,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
//if (
//      (!preg_match('/^[[:digit:]]{4}-[[:digit:]]{2,3}(-[[:alnum:]\-]+)?$/i',$div_spec))
//   ||
//      (!preg_match('/^[[:alnum:]][[:alnum:]\-_]*$/i',$frame_num))
//   )
//   {
//   echo "Improperly-formatted request";
//   exit;
//   }
//
require_once("f_bodyopen.phtml");
require_once("f_purgestalesearches.phtml");
require_once('f_putstdrecaptchablock.phtml');
require_once('f_putstdrecaptchaheadscriptreference.phtml');
require_once('f_standardexifoutput.phtml');
//
$ini = AppSettings();
$db_link = DbLink($ini);
//
// Increment the hit count.
//
$db_link->query("update low_priority photo_detail set hits = hits + 1 where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
//
// Retrieve the photo_detail row.
//
$result_set = $db_link->query("select id, be_avail_as_huge, caption, tech_details, copyright_year, hits, keywords from photo_detail where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
//
// Check how many rows were returned
//
$rows = mysqli_num_rows($result_set);
if ((!$result_set) || ($rows != 1))
   {
   //
   // No connection or no rows returned.
   //
   $record_found = 0;
   $db_link->query("alter table photo_detail drop column id");
   $db_link->query
      (
      //
      // Will still fail if the given div_spec or frame_num exceed allowed lengths.
      //
      "insert into photo_detail"
      . " set div_spec=\"$div_spec\""
      .   " , frame_num=\"$frame_num\""
      .   " , be_avail_as_huge='Y'"
      .   " , caption=\"Photograph DIV-$div_spec/$frame_num\""
      .   " , tech_details='No technical details recorded'"
      .   " , hits=1"
      .   " , era=6"
      );
   $db_link->query("alter table photo_detail order by div_spec,frame_num");
   $db_link->query("alter table photo_detail add column id serial first");
   $result_set = $db_link->query("select id, be_avail_as_huge, caption, tech_details, copyright_year, hits, keywords from photo_detail where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
   }
else
   {
   $record_found = 1;
   }
$fields = mysqli_fetch_array($result_set);
if ($fields) extract($fields);
$exif = StandardExifOutput($div_spec,$frame_num);
if ($exif) $tech_details = $exif; 
$photo_size = GetImageSize("../photo/div/$div_spec/$frame_num-3.jpg");
$comment_result_set = $db_link->query("select nickname, email_address, text from photo_comment where div_spec=\"$div_spec\" and frame_num=\"$frame_num\"");
$num_comments = mysqli_num_rows($comment_result_set);
//
if ($search_id)
   {
   $db_link->query("update search_manifest set time_of_last_reference = now() where id = '$search_id'") or die("Failure updating search manifest");
   $search_id_found = ($db_link->affected_rows > 0);
   PurgeStaleSearches($db_link);
   }
?>
<html>
   <head>
      <title>Photo Exhibit [div/<? echo $div_spec ?>/<? echo $frame_num ?>]</title>
      <? PutStdReCaptchaHeadScriptReference(); ?>
   </head>
   <? BodyOpen(); ?>
      <H6 align="center">
         <a href="<? echo $ini[app][my_home_page_url]; ?>">Kevin Andrew Lipscomb</a>
         -
         <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a>
         -
         <a href="<? echo $ini[server][root_url]; ?>/browse_divs.phtml">Digital Image Volumes</a>
         -
         <a href="<? echo $ini[server][root_url]; ?>/browse_frames.phtml?div_spec=<? echo $div_spec ?>"><? echo $div_spec ?></a>
      </H6>
      <table border="0" cellpadding="10" cellspacing="0" width="100%" align="center">
         <tr>
            <td align="right" height="33" valign="top">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               if ($id > 1)
                  {
                  extract(@mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec, frame_num as prior_frame_frame_num from photo_detail where id = $id - 1")));
                  echo "<a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$prior_frame_div_spec&frame_num=$prior_frame_frame_num><br/>Prior<br/>div/frame<br/>&nbsp;</a>";
                  }
               else
                  {
                  echo "<p><br></p>";
                  }
               if ($search_id_found && ($result_num > 1))
                  {
                  extract(@mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec, frame_num as prior_frame_frame_num from search_result_$search_id where result_num = $result_num - 1")));
                  echo "<p><a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$prior_frame_div_spec&frame_num=$prior_frame_frame_num&search_id=$search_id&result_num=" . ($result_num - 1) . "&num_results=$num_results><br/>Prior<br/>search<br/>result<br/>&nbsp;</a></p>";
                  }
               else
                  {
                  echo "<p><br><br></p>";
                  }
               if ($num_comments)
                  {
                  $arrow_size = GetImageSize("arrow.gif");
                  echo "<p><a href=#Comments><img border=0 align=top src=arrow.gif $arrow_size[3] alt=\"This exhibit has an anecdote or comment thread.\"></a></p>";
                  }
               ?>
               </tt>
            </td>
            <td align="center" width="784">
               <?
               echo "<img border=8 align=top src=" . $ini[server][photodb_prefix] . "div/$div_spec/$frame_num-3.jpg $photo_size[3]>";
               ?>
            </td>
            <td height="33" valign="top">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               extract(mysqli_fetch_array($db_link->query("select max(id) as max_id from photo_detail")));
               if ($id < $max_id)
                  {
                  extract(@mysqli_fetch_array($db_link->query("select div_spec as next_frame_div_spec, frame_num as next_frame_frame_num from photo_detail where id = $id + 1")));
                  echo "<a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$next_frame_div_spec&frame_num=$next_frame_frame_num><br/>Next<br/>div/frame<br/>&nbsp;</a>";
                  }
               else
                  {
                  echo "<p><br></p>";
                  }
               if ($search_id_cound && ($result_num < $num_results))
                  {
                  extract(@mysqli_fetch_array($db_link->query("select div_spec as next_frame_div_spec, frame_num as next_frame_frame_num from search_result_$search_id where result_num = $result_num + 1")));
                  echo "<p><a style=\"font-size:larger; display:block; height:100%; width:100%;\" href=" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$next_frame_div_spec&frame_num=$next_frame_frame_num&search_id=$search_id&result_num=" . ($result_num + 1) . "&num_results=$num_results><br/>Next<br/>search<br/>result<br/>&nbsp;</a></p>";
                  }
               ?>
               </tt>
            </td>
         </tr>
      </table>
      <table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
         <tr>
            <td>
               <?
               if ($record_found)
                  {
                  echo "<p align=center><i><b>$caption</b></i></p>\n";
                  echo "<p align=center>$tech_details</p>\n";
                  }
               echo "<small><ul>";
               if (!$record_found or ($be_avail_as_huge == "Y"))
                  {
                  echo "<li>Also available online as a <a href=\"" . $ini[server][photodb_prefix] . "div/$div_spec/$frame_num-4.jpg\">1.5 megapixel JPEG</a> (recommended for desktop wallpaper, screen-saver, or 5x7 inch <a href=methods.phtml#Printing>dye sub prints</a>).";
                  echo "<li><a href=\"mailto:kevin.lipscomb@kvrs.org\">Email me</a> about larger prints or digital resolutions up to 6 megapixels.";
                  }
               if ($record_found)
                  {
                  if ($hits == 1)
                     {
                     echo "<li>Viewed 1 time.";
                     }
                  else
                     {
                     echo "<li>Viewed $hits times.";
                     }
                  }
               else
                  {
                  echo "<li>No database record for this photograph existed, so a generic record has now been inserted.&nbsp; Please consider adding some keywords (below).";
                  }
               echo "<li>This and <a href=\"index.phtml\">other photographs</a> copyright $copyright_year <a href=\"" . $ini[app][my_home_page_url] . "\">Kevin Andrew Lipscomb</a>";
               echo "<li>To improve searchability, the following keywords are also associated with this photograph.&nbsp; Click on a word to perform a search on it.&nbsp; If you can think of other applicable words that aren't already in the caption or the technical details, please enter them in the field below.<br><br>\n";
               echo "<i>\n";
               $keyword_array = explode(" ",$keywords);
               foreach($keyword_array as $keyword)
                  {
                  echo "<a href=search_result.phtml?basic_criteria=$keyword>$keyword</a>\n";
                  }
               echo "</i><br><br>\n";
               echo "<form action=add-keywords.phtml?div_spec=$div_spec&frame_num=$frame_num method=post>\n";
               echo    "<table border=0 cellpadding=5 cellspacing=0>\n";
               echo       "<tr>\n";
               echo          "<td valign=top>New keyword(s): <input name=new_keywords type=text></td>\n";
               echo          "<td valign=top>\n";
               if (!$ini[app][be_d]) PutStdReCaptchaGetBlock();
               echo          "</td>\n";
               echo          "<td valign=top><input type=submit value=\"Submit\"></td>\n";
               echo       "</tr>\n";
               echo    "</table>\n";
               echo "</form>\n";
               echo "</ul></small>\n";
               echo "<hr>\n";
               echo "<p align=center><a name=Comments></a><b>Anecdote and Comment Area</b></p>\n";
               for ($comment_num = 1; $comment_num <= $num_comments; $comment_num++)
                  {
                  $comment_field_array = mysqli_fetch_array($comment_result_set);
                  extract($comment_field_array);
                  if ($nickname == "") $nickname = $email_address;
                  echo "<p><tt>" . stripslashes($text) . "</tt>";
                  if ($nickname != "")
                     {
                     echo "&nbsp; -- <i><a href=mailto:$email_address>$nickname</a></i>";
                     }
                  echo "</p>\n";
                  }
               echo"<p align=center><i><a href=collect-comment.phtml?div_spec=$div_spec&frame_num=$frame_num>Add an anecdote or comment</a></i></p>\n";
               ?>
            </td>
         </tr>
      </table>
   </body>
</html>
