<?
require_once("f_putlibphotorandomkeyed.phtml");
require_once("f_bodyopen.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>

<html>

<head>
<title>Photography - Travel</title>
</head>

<? BodyOpen(); ?>

<table align=center border="0" cellpadding="0" cellspacing="0" width="80%">
  <tr>
    <td width="100%"><h5 align="center"><a href="<? echo $ini[app][my_home_page_url]; ?>">Kevin Andrew Lipscomb</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></h5>
      <h1 align="center">Travel</h1>
      <p align="center">
      <? PutLibPhotoRandomKeyed($ini,$db_link,"%travel%"); ?>
      </p>
    </td>
  </tr>
</table>
</body>
</html>
