<?
//
// $Id: f_connectselectdb.phtml 578 2002-03-11 19:53:12Z kevinanlipscomb $
//
function DbkalipsoLink($ini)
   {
   $saved_error_level = error_reporting(E_ALL);
   $dbkalipso_link = mysqli_init();
   $success = $dbkalipso_link->real_connect($ini[dbkalipso][server],$ini[dbkalipso][uid],$ini[dbkalipso][pwd],$ini[dbkalipso][database])
      or die("ERRNO-" . mysqli_connect_errno() . ", " . mysqli_connect_error());
   $success = $success && (mysqli_connect_error() == NULL);
   error_reporting($saved_error_level);
   return $dbkalipso_link;
   }
?>
