<?php
//
// $Id: whats-new.phtml 7054 2020-04-18 17:02:08Z kevinanlipscomb $
//
?>
<html>
  <head><title>KVEO-IT-PROJECT - Foundation Class Library - What's New</title></head>
  <body bgcolor=#ffffff>
    <table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
      <tr>
        <td>
          <h6 align="center">KVEO-IT-PROJECT</h6>
          <h6 align="center">FOUNDATION CLASS LIBRARY</h6>
          <h1 align="center">What's New</h1>
          <hr>
          <p><b>2002-07-19:&nbsp; </b>Minor rendition change to AolEmailClientWarning.</p>
          <p><b>2002-07-18:&nbsp; </b>Initiated the Foundation Class Library by creating the STD_STYLE_CLASS, whose first
            operation, AolEmailClientWarning, returns an appropo warning modeled after an interstate highway caution
            sign.&nbsp; Added operation CatchUpBlurb to provide a standard way to link to this What's New file.</p>
          <hr>
          <p><small><small><em><pre>$Id: whats-new.phtml 7054 2020-04-18 17:02:08Z kevinanlipscomb $</pre></em></small></small></p>
        </td>
      </tr>
    </table>
  </body>
</html>
