<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Make parameters safe and validate them
//
if (isset($div_spec)) $div_spec = kix\k::Safe($div_spec,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
if (isset($email_address)) $email_address = kix\k::Safe($email_address,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
if (isset($frame_num)) $frame_num = kix\k::Safe($frame_num,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_UNDERSCORED_ALPHANUM"));
if (isset($nickname)) $nickname = kix\k::Safe($nickname,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
if (isset($text)) $text = kix\k::Safe($text,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
//
require_once('f_confirmrecaptchaanswerordie.phtml');
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
//
// Connect to the database.
//
ParseIniAndConnectSelectDbInstance($ini,$db_link);
?>
<html>
<head><title>Anecdote/comment addition [div/<? echo $div_spec ?>/<? echo $frame_num ?>]</title></head>
<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
         <H6 ALIGN="CENTER"><a href="<? echo $ini[app][my_home_page_url]; ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></H6>
         <H1 ALIGN="CENTER">Anecdote/comment addition</H1>
         <hr>
         <?
         PutLibPhoto($ini,$db_link,$div_spec,$frame_num,"left");
         if (!$ini[app][be_d]) ConfirmReCaptchaAnswerOrDie();
         //
         // Create and execute the SQL statement to increment the hit count.
         //
         $sql = "insert into photo_comment set div_spec='$div_spec', frame_num='$frame_num', nickname='$nickname', email_address='$email_address', text='$text'";
         $db_link->query($sql) or die("Sorry, the database query did not succeed.");
         kix\k::SmtpMailSend
            (
            "photolib@frompaper2web.com", //from
            "kevin.lipscomb@kvrs.org", //to
            "New photograph anecdote or comment", //subject
            stripslashes //message_string
               (
               "The \'Kevin Andrew Lipscomb - Photography - add-comment.phtml\' script has processed the following"
                  .  " operation:\n\n"
                  .  $sql
                  .  "\n\n"
                  .  "See <" . $ini[server][root_url] . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>."
               )
            );
         ?>
         <b>Thanks!</b></p>
         <p>Your anecdote or comment has been added to the presentation page for this photograph.  You can click on the thumbnail to the left to see that your submission has indeed been added.</p>
      </td>
   </tr>
</table>
</body>
</html>
