<!DOCTYPE html>
<html>
  <head>
    <!-- $Id: exception.aspx 7117 2020-05-06 00:00:59Z kevinanlipscomb $ -->
    <title></title>
  </head>
  <body bgcolor="white">
    <table id="Table_dangerous_input" bordercolor="#dcdcdc" cellspacing="0" cellpadding="0" border="1">
      <tr>
        <td>
          <table cellspacing="0" cellpadding="10" border="0">
            <tr><td bgcolor="#f5f5f5"><h1><em>Hold on...</em></h1></td></tr>
            <tr>
              <td>
                <h3>You entered something that resembles a hacking attempt.</h3>
                <p>For security reasons, you are not allowed to input the following special character combinations into this system:</p>
                <blockquote>
                  <table cellpadding="10" cellspacing="0" border="1">
                    <tr style="background-color:gainsboro">
                      <td>Bad input</td>
                      <td>Description</td>
                    </tr>
                    <tr>
                      <td align="center"><big><big><b>&lt;</b></big></big></td>
                      <td><i>XML/HTML tag start token</i></td>
                    </tr>
                    <tr>
                      <td align="center"><big><big><b>&amp;#</b></big></big></td>
                      <td><i>XML/HTML numeric character reference</i></td>
                    </tr>
                  </table>
                </blockquote>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
