<?
require_once("f_myhomepageurl.phtml");
require_once("f_mymainphotopageurl.phtml");
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
?>

<html>

<head>
<title>Photography - Expeditions</title>
</head>

<? BodyOpen(); ?>
<div align="center"><center>

<table border="0" cellpadding="0" cellspacing="0" width="80%">
  <tr>
    <td width="100%"><h5 align="center"><a href="<? echo MyHomePageUrl(); ?>">Kevin Andrew Lipscomb</a> - <a href="<? echo MyMainPhotoPageUrl(); ?>">Photography</a></h5>
    <h1 align="center">Expeditions</h1>
      <p>
      <? PutLibPhoto("2001-003","030","left"); ?>
      <a href="indian-river-park.phtml">Indian River Park, Chesapeake, Virginia</a>
      </p>
</center>
    </td>
  </tr>
</table>
  </div><div align="center"><center>

<pre><small><small>$Id$</small></small></pre>
</center></div>
</body>
</html>
