<?php
//
require_once('../../foundation/f_recaptchaprivatekey.phtml');
require('../../foundation/recaptcha-master/src/autoload.php');
//
function ConfirmReCaptchaAnswerOrDie()
  {
  $recaptcha = new \ReCaptcha\ReCaptcha(ReCaptchaPrivateKey());
  $resp = $recaptcha->verify($_POST['g-recaptcha-response'],$_SERVER['REMOTE_ADDR']);
  if ($resp->isSuccess())
    {
    // verified!
    // if Domain Name Validation turned off don't forget to check hostname field
    // if($resp->getHostName() === $_SERVER['SERVER_NAME']) {  }
    }
  else
    {
    echo "<pre>";
    var_dump($resp);
    echo "</pre>";
    die ("The reCAPTCHA wasn't entered correctly.  Debug info is shown above.  Go back and try it again.");
    }
  }
?>