<?php
//
require_once("recaptcha-master/src/ReCaptcha/ReCaptcha.php");
//
function ConfirmReCaptchaAnswerOrDie($ini)
  {
  $recaptcha = new ReCaptcha\ReCaptcha($ini[recaptcha][private_key]);
  $resp = $recaptcha->verify($_POST['g-recaptcha-response'],$_SERVER['REMOTE_ADDR']);
  if ($resp->isSuccess())
    {
    // verified!
    // if Domain Name Validation turned off don't forget to check hostname field
    // if($resp->getHostName() === $_SERVER['SERVER_NAME']) {  }
    }
  else
    {
    echo "<pre>";
    var_dump($resp);
    echo "</pre>";
    die ("The reCAPTCHA wasn't entered correctly.  Debug info is shown above.  Go back and try it again.");
    }
  }
?>