<?php
require_once('../../foundation/recaptchalib.php');
require_once('../../foundation/f_recaptchaprivatekey.phtml');
function ConfirmReCaptchaAnswerOrDie()
  {
  $resp = recaptcha_check_answer
    (
    ReCaptchaPrivateKey(),
    $_SERVER["REMOTE_ADDR"],
    $_POST["recaptcha_challenge_field"],
    $_POST["recaptcha_response_field"]
    );
  if (!$resp->is_valid)
    {
    die ("The reCAPTCHA wasn't entered correctly. Go back and try it again.  (reCAPTCHA said: " . $resp->error . ")");
    }
  }
?>