<?
//
// $Id: f_connectselectdb.phtml 578 2002-03-11 19:53:12Z kevinanlipscomb $
//
function DbLink($ini)
   {
   $saved_error_level = error_reporting(E_ALL);
   $db_link = mysqli_init();
   $success = $db_link->real_connect($ini[db][server],$ini[db][uid],$ini[db][pwd],$ini[db][database])
      or die("ERRNO-" . mysqli_connect_errno() . ", " . mysqli_connect_error());
   $success = $success && (mysqli_connect_error() == NULL);
   error_reporting($saved_error_level);
   return $db_link;
   }
?>
