<?
//
// $Id$
//
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_myphotolibhosturl.phtml");
//
function PutLibPhoto
   (
   $div_spec,
   $frame_num,
   $alignment = "",
   $search_id = "",
   $result_num = "",
   $num_results = ""
   )
   {
   $image_source_spec = "div/$div_spec/$frame_num-i.jpg";
   echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num&search_id=$search_id&result_num=$result_num&num_results=$num_results>";
   $size = @GetImageSize("$image_source_spec");
   echo "<img border=\"2\" src=\"$image_source_spec\" align=\"$alignment\" $size[3]>";
   echo "</a>";
   //
   ConnectSelectDbInstanceUNPUBLISHED($db_link);
   $result_set = $db_link->query("select TRUE from photo_detail where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
   $rows = mysqli_num_rows($result_set);
   if ((!$result_set) || ($rows != 1))
      {
      //
      // No connection or no rows returned.
      //
      $db_link->query("alter table photo_detail drop column id");
      $db_link->query
         (
         "insert into photo_detail"
         . " set div_spec=\"$div_spec\""
         .   " , frame_num=\"$frame_num\""
         .   " , be_avail_as_huge='Y'"
         .   " , caption=\"Photograph DIV-$div_spec/$frame_num\""
         .   " , tech_details='No technical details recorded'"
         .   " , hits=1"
         .   " , era=6"
         );
      $db_link->query("alter table photo_detail order by div_spec,frame_num");
      $db_link->query("alter table photo_detail add column id serial first");
      }
   }
?>