<?php
//
// Note that you should accompany a call to this function with a call to PutStdReCaptchaHeadScriptReference() just before the </head> tag.
//
function PutStdReCaptchaGetBlock()
  {
  echo "<table border=1 cellpadding=5 cellspacing=0><tr><td>Please prove that you're a human...";
  echo "<div class='g-recaptcha' data-sitekey='6LdZFtYSAAAAACY7QxxpWSpQjv7swOq-LFuQGQwy'></div>";
  echo "</td></tr></table>";
  }
?>