<?
//
// $Id$
//
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_myphotolibhosturl.phtml");
//
function PutLibPhotoPlaced($placement)
   {
   if (isset($placement)) $placement = kix\k::Safe($placement,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHA_WORDS"));
   //
   // Connect to the database.
   //
   $conn = ConnectSelectDbInstanceUNPUBLISHED($db_link);
   $instance = Instance($db_link);
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail where placement like '%$placement%' order by rand()";
   //
   // Execute the statement
   //
   $result_set = $db_link->query($sql);
   //
   // Check how many rows were returned
   //
   $rows = mysqli_num_rows($result_set);
   if ((!$result_set) || ($rows == 0))
      {
      echo "<br><b>Could not find any such photographs.</b><br>";
      }
   else
      {
      //
      while ($field_array = mysqli_fetch_array($result_set))
         {
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = "$instance[photodb_prefix]div/$div_spec/$frame_num-i.jpg";
         echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num>\n";
         $size = @GetImageSize("$image_source_spec");
         echo "   <img border=\"2\" src=\"$image_source_spec\" $size[3]>\n";
         echo "</a>\n";
         }
      }
   }
?>
