<?
//
// $Id$
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
//
// Make parameters safe and validate them
//
if (isset($visitor)) $visitor = kix\k::Safe($visitor,kix\k::PhpValueOf_safe_hint_type("HEX"));
//
require_once("f_putlibphoto.phtml");
require_once("f_bodyopen.phtml");
//
ParseIniAndConnectSelectDbInstance($ini,$db_link);
//
if ($remember_visitor)
   {
   //
   // Drop a cookie containing the user's Site ID String.  The
   // cookie expires 10 years from the current time.
   //
   setcookie("raw_visitor_id_cookie",$visitor,time()+315360000);
   }
else
   {
   //
   // Instead of dropping a cookie, trigger the removal of any
   // lingering cookie that we previously dropped.
   //
   setcookie("raw_visitor_id_cookie","",time()-3600);
   }
?>
<html>
<head><title>New Photographs</title></head>
<? BodyOpen(); ?>
<table align=center width="80%"><tr><td>
<H6 ALIGN="CENTER"><a href="<? echo $ini[app][my_home_page_url]; ?>">KEVIN ANDREW LIPSCOMB</a> - <a href="<? echo $ini[server][main_page_url]; ?>">Photography</a></H6>
<H1 ALIGN="CENTER">New Photographs</H1>
<hr>
<p><b>The following Digital Image Volumes have been added or updated since your last visit:</b></p>
<?
//
// Get the time of the user's last visit.
//
$visitor = hash('sha256',$visitor);
$result = $db_link->query("select time from visit where visitor = '$visitor'");
$num_rows = mysqli_num_rows($result);
if ($num_rows == 0)
   {
   //
   // If no such visitor was located, they are new to us.  Set the time of their
   // last visit to zero.  Everything will be newer than that.
   //
   $time = 0;
   }
else
   {
   //
   // Otherwise there can only be one row because visitors are unique in the visit table.
   //
   $row = mysqli_fetch_object($result);
   $time = $row->time;
      //
      // Sets up the $time variable.
      //
   }
//
// Walk through the DIV structure looking for folders or files added or modified since user's last visit.
//
echo "<ul>";
$div_dir = dir("div");
$found = 0;
while ($subdir_entry = $div_dir->read())
   {
   if (!strstr($subdir_entry,"."))
      {
      $list_item = "<li><a href=" . $ini[server][root_url] . "/browse_frames.phtml?div_spec=$subdir_entry>$subdir_entry</a>";
      if (filemtime("div/$subdir_entry") > $time)
         {
         echo "$list_item\n";
         $found = 1;
         }
      else
         {
         $subdir = dir("div/$subdir_entry");
         while ($jpg_entry = $subdir->read())
            {
            if (!strstr($jpg_entry,"."))
               {
               if (filemtime("div/$subdir_entry/$jpg_entry") > $time)
                  {
                  echo "$list_item\n";
                  $found = 1;
                  }
               }
            }
         $subdir->close();
         }
      }
   }
if (!$found)
   {
   echo "<li>None\n";
   }
echo "</ul>";
$div_dir->close();
?>
<form action=mark-visit.phtml method=post>
   <input type=submit value="Mark above entries as OLD">
   <input type=hidden name=visitor value="<? echo $visitor; ?>">
</form>
</td></tr></table>
</body>
</html>
