<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals')) {
    $superglobals = array($_SERVER, $_ENV,
        $_FILES, $_COOKIE, $_POST, $_GET);
    if (isset($_SESSION)) {
        array_unshift($superglobals, $_SESSION);
    }
    foreach ($superglobals as $superglobal) {
        extract($superglobal, EXTR_SKIP);
    }
}
//
// Validate parameters
//
if (sscanf($div_spec,"%1d%1d%1d%1d-%1d%s",&$d11,&$d12,&$d13,&$d14,&$d15,&$d16) != 6)
   {
   echo "Improperly-formatted request";
   exit;
   }
require_once("f_bodyopen.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_myhomepageurl.phtml");
require_once("f_mymainphotopageurl.phtml");
require_once("f_myphotolibhosturl.phtml");
require_once("f_purgestalesearches.phtml");
require_once('f_putstdrecaptchablock.phtml');
//
// Connect to the database.
//
ConnectSelectDbInstanceUNPUBLISHED($db_link);
//
// Increment the hit count.
//
$db_link->query("update low_priority photo_detail set hits = hits + 1 where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
//
// Retrieve the photo_detail row.
//
$result_set = $db_link->query("select id, be_avail_as_huge, caption, tech_details, copyright_year, hits, keywords from photo_detail where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
//
// Check how many rows were returned
//
$rows = mysqli_num_rows($result_set);
if ((!$result_set) || ($rows != 1))
   {
   //
   // No connection or no rows returned.
   //
   $record_found = 0;
   $db_link->query("alter table photo_detail drop column id");
   $db_link->query
      (
      "insert into photo_detail"
      . " set div_spec=\"$div_spec\""
      .   " , frame_num=\"$frame_num\""
      .   " , be_avail_as_huge='Y'"
      .   " , caption=\"Photograph DIV-$div_spec/$frame_num\""
      .   " , tech_details='No technical details recorded'"
      .   " , hits=1"
      .   " , era=6"
      );
   $db_link->query("alter table photo_detail order by div_spec,frame_num");
   $db_link->query("alter table photo_detail add column id serial first");
   $result_set = $db_link->query("select id, be_avail_as_huge, caption, tech_details, copyright_year, hits, keywords from photo_detail where div_spec = \"$div_spec\" and frame_num = \"$frame_num\"");
   }
else
   {
   $record_found = 1;
   }
extract(mysqli_fetch_array($result_set));
$photo_size = GetImageSize("div/$div_spec/$frame_num-3.jpg");
$comment_result_set = $db_link->query("select nickname, email_address, text from photo_comment where div_spec=\"$div_spec\" and frame_num=\"$frame_num\"");
$num_comments = mysqli_num_rows($comment_result_set);
//
if ($search_id)
   {
   $db_link->query("update search_manifest set time_of_last_reference = now() where id = '$search_id'") or die("Failure updating search manifest");
   PurgeStaleSearches($db_link);
   }
?>
<html>
   <head>
      <title>Photo Exhibit [div/<? echo $div_spec ?>/<? echo $frame_num ?>]</title>
   </head>
   <? BodyOpen(); ?>
      <H6 align="center">
         <a href="<? echo MyHomePageUrl(); ?>">KEVIN ANDREW LIPSCOMB</a>
         -
         <a href="<? echo MyMainPhotoPageUrl(); ?>">Photography</a>
         -
         <a href="<? echo MyPhotoLibHostUrl(); ?>/browse_divs.phtml">Digital Image Volumes</a>
         -
         <a href="<? echo MyPhotoLibHostUrl(); ?>/browse_frames.phtml?div_spec=<? echo $div_spec ?>"><? echo $div_spec ?></a>
      </H6>
      <table border="0" cellpadding="10" cellspacing="0" width="100%" align="center">
         <tr>
            <td align="right" height="33" valign="top">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               if ($id > 1)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec, frame_num as prior_frame_frame_num from photo_detail where id = $id - 1")));
                  echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$prior_frame_div_spec&frame_num=$prior_frame_frame_num>Prior<br>div/frame</a>";
                  }
               else
                  {
                  echo "<p><br></p>";
                  }
               if ($result_num > 1)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as prior_frame_div_spec, frame_num as prior_frame_frame_num from search_result_$search_id where result_num = $result_num - 1")));
                  echo "<p><a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$prior_frame_div_spec&frame_num=$prior_frame_frame_num&search_id=$search_id&result_num=" . ($result_num - 1) . "&num_results=$num_results>Prior<br>search<br>result</a></p>";
                  }
               else
                  {
                  echo "<p><br><br></p>";
                  }
               if ($num_comments)
                  {
                  $arrow_size = GetImageSize("arrow.gif");
                  echo "<p><a href=#Comments><img border=0 align=top src=arrow.gif $arrow_size[3] alt=\"This exhibit has an anecdote or comment thread.\"></a></p>";
                  }
               ?>
               </tt>
            </td>
            <td align="center" width="784">
               <?
               echo "<img border=8 align=top src=div/$div_spec/$frame_num-3.jpg $photo_size[3]>";
               ?>
            </td>
            <td height="33" valign="top">
               <tt>
               <?
               echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>";
               extract(mysqli_fetch_array($db_link->query("select max(id) as max_id from photo_detail")));
               if ($id < $max_id)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as next_frame_div_spec, frame_num as next_frame_frame_num from photo_detail where id = $id + 1")));
                  echo "<a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$next_frame_div_spec&frame_num=$next_frame_frame_num>Next<br>div/frame</a>";
                  }
               else
                  {
                  echo "<p><br></p>";
                  }
               if ($result_num < $num_results)
                  {
                  extract(mysqli_fetch_array($db_link->query("select div_spec as next_frame_div_spec, frame_num as next_frame_frame_num from search_result_$search_id where result_num = $result_num + 1")));
                  echo "<p><a href=" . MyPhotoLibHostUrl() . "/present-photo.phtml?div_spec=$next_frame_div_spec&frame_num=$next_frame_frame_num&search_id=$search_id&result_num=" . ($result_num + 1) . "&num_results=$num_results>Next<br>search<br>result</a></p>";
                  }
               ?>
               </tt>
            </td>
         </tr>
      </table>
      <table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
         <tr>
            <td>
               <?
               if ($record_found)
                  {
                  echo "<p align=center><i><b>$caption</b></i></p>\n";
                  echo "<p align=center>$tech_details</p>\n";
                  }
               echo "<small><ul>";
               if (!$record_found or ($be_avail_as_huge == "Y"))
                  {
                  echo "<li>Also available online as a <a href=\"div/$div_spec/$frame_num-4.jpg\">1.5 megapixel JPEG</a> (recommended for desktop wallpaper, screen-saver, or 5x7 inch <a href=methods.phtml#Printing>dye sub prints</a>).";
                  echo "<li><a href=\"mailto:kevin.lipscomb@kvrs.org\">Email me</a> about larger prints or digital resolutions up to 6 megapixels.";
                  }
               if ($record_found)
                  {
                  if ($hits == 1)
                     {
                     echo "<li>Viewed 1 time.";
                     }
                  else
                     {
                     echo "<li>Viewed $hits times.";
                     }
                  }
               else
                  {
                  echo "<li>No database record for this photograph existed, so a generic record has now been inserted.&nbsp; Please consider adding some keywords (below).";
                  }
               echo "<li>This and <a href=\"index.phtml\">other photographs</a> copyright $copyright_year <a href=\"" . MyHomePageUrl() . "\">Kevin Andrew Lipscomb</a>";
               echo "<li>To improve searchability, the following keywords are also associated with this photograph.&nbsp; Click on a word to perform a search on it.&nbsp; If you can think of other applicable words that aren't already in the caption or the technical details, please enter them in the field below.<br><br>\n";
               echo "<i>\n";
               $keyword_array = split(" ",$keywords);
               foreach($keyword_array as $keyword)
                  {
                  echo "<a href=search_result.phtml?basic_criteria=$keyword>$keyword</a>\n";
                  }
               echo "</i><br><br>\n";
               echo "<form action=add-keywords.phtml?div_spec=$div_spec&frame_num=$frame_num method=post>\n";
               echo    "<table border=0 cellpadding=5 cellspacing=0>\n";
               echo       "<tr>\n";
               echo          "<td valign=top>New keyword(s): <input name=new_keywords type=text></td>\n";
               echo          "<td valign=top>\n";
               PutStdReCaptchaGetBlock();
               echo          "</td>\n";
               echo          "<td valign=top><input type=submit value=\"Submit\"></td>\n";
               echo       "</tr>\n";
               echo    "</table>\n";
               echo "</form>\n";
               echo "</ul></small>\n";
               echo "<hr>\n";
               echo "<p align=center><a name=Comments></a><b>Anecdote and Comment Area</b></p>\n";
               for ($comment_num = 1; $comment_num <= $num_comments; $comment_num++)
                  {
                  $comment_field_array = mysqli_fetch_array($comment_result_set);
                  extract($comment_field_array);
                  if ($nickname == "") $nickname = $email_address;
                  echo "<p><tt>" . stripslashes($text) . "</tt>";
                  if ($nickname != "")
                     {
                     echo "&nbsp; -- <i><a href=mailto:$email_address>$nickname</a></i>";
                     }
                  echo "</p>\n";
                  }
               echo"<p align=center><i><a href=collect-comment.phtml?div_spec=$div_spec&frame_num=$frame_num>Add an anecdote or comment</a></i></p>\n";
               ?>
            </td>
         </tr>
      </table>
   </body>
</html>
